"""Build data/site-code-crosswalk.json from the Kobo form's site.csv media
attachment.

The form's site list (select_one_from_file site.csv) keys sites by codes that
do not always exist in the CCCM master list (agency-prefixed ACTEDSO…, stale
codes from older list versions). Records submitted with those codes were
landing as Unmatched even though the enumerator picked the site from a list.

Resolution here is by NAME + DISTRICT, never by parsing the code — parsing was
measured against the live payload and bound records to the wrong site (see
api/lib/site_matching.py module docstring). A crosswalk entry is emitted only
when the site.csv row's label resolves to exactly ONE master site; anything
ambiguous is skipped and stays visibly unmatched.

Usage: python scripts/build_site_code_crosswalk.py path/to/site.csv
"""

from __future__ import annotations

import csv
import json
import sys

sys.path.insert(0, ".")

from api.lib.site_matching import get_master_site_index, _strip_temp_marker, _normalize_name  # noqa: E402
from api.lib.transformations import resolve_district  # noqa: E402


def main(site_csv_path: str) -> None:
    idx = get_master_site_index("data/master-sites.csv")
    rows = [
        r for r in csv.DictReader(open(site_csv_path, encoding="utf-8-sig"))
        if str(r.get("name", "")).strip().upper() != "OTHER"
    ]

    crosswalk: dict[str, str] = {}
    skipped_ambiguous = skipped_no_name = already_direct = 0
    for r in rows:
        code = str(r["name"]).strip().upper()
        label = str(r.get("label") or r.get("site_label") or "").strip()
        district_pcode = str(r.get("districtfilter") or "").strip()

        if code in idx.by_id or _strip_temp_marker(code) in idx.by_id_normalized:
            already_direct += 1
            continue  # matcher already handles it — no entry needed

        district_name, _ = resolve_district(district_pcode)
        candidates = idx.by_name.get(_normalize_name(label), [])
        in_district = [
            c for c in candidates
            if district_name and _normalize_name(c.district) == _normalize_name(district_name)
        ]
        if len(in_district) == 1:
            crosswalk[code] = in_district[0].cccm_site_id
        elif len(candidates) == 1:
            crosswalk[code] = candidates[0].cccm_site_id
        elif candidates:
            skipped_ambiguous += 1
        else:
            skipped_no_name += 1

    out = {
        "_comment": (
            "Kobo form site.csv code -> master CCCM Site ID. Generated by "
            "scripts/build_site_code_crosswalk.py; resolution is by site name "
            "+ district against the master list (never by parsing the code). "
            "Regenerate whenever the form's site.csv or the master list changes."
        ),
        "entries": dict(sorted(crosswalk.items())),
    }
    with open("data/site-code-crosswalk.json", "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1, ensure_ascii=False)
    print(
        f"Wrote data/site-code-crosswalk.json: {len(crosswalk)} entries "
        f"(direct-matchable skipped: {already_direct}, ambiguous skipped: {skipped_ambiguous}, "
        f"label not in master: {skipped_no_name})"
    )


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "ML/site.csv")
