"""Generate data/form-sites.json — the Kobo form's own site choice list.

Submissions carry the choice-list *code* in `group_general_info/site_name`
(e.g. "ACTEDSO1401_55"), not a site name. Without this lookup the dashboard
shows an opaque code and the name-matching tiers of site resolution have
nothing to work with, so a site reference can only ever match by exact ID.

The label in the form IS authoritative for what the enumerator selected — it
is the text they saw and picked. Resolving code -> label is therefore reading
the source correctly, not guessing: it never asserts a master-list identity,
it only recovers the name that was already chosen.

    python scripts/build_form_sites.py [ML/site.csv]
"""

from __future__ import annotations

import csv
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "form-sites.json")


def build(src: str) -> dict:
    with open(src, encoding="utf-8-sig") as fh:
        rows = list(csv.DictReader(fh))

    sites: dict[str, dict] = {}
    for row in rows:
        code = (row.get("name") or "").strip()
        label = (row.get("label") or row.get("site_label") or "").strip()
        if not code or not label or code == label:
            continue
        district = (row.get("districtfilter") or "").strip() or None
        catchment = (row.get("subdistrict_filter") or "").strip() or None
        # "SO1401none" is the form's way of saying "no catchment for this site".
        if catchment and catchment.lower().endswith("none"):
            catchment = None
        sites[code] = {"label": label, "districtPcode": district, "catchmentCode": catchment}
    return sites


def main() -> None:
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "ML", "site.csv")
    sites = build(src)
    payload = {
        "_comment": (
            "Generated by scripts/build_form_sites.py from the Kobo form's site "
            "choice list. Maps the submitted choice CODE to the LABEL the "
            "enumerator actually selected. Recovering the name is not a "
            "master-list match — resolution against the CCCM master list is a "
            "separate, evidence-based step."
        ),
        "source": os.path.basename(src),
        "count": len(sites),
        "sites": sites,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1, sort_keys=True)
        fh.write("\n")
    print(f"{len(sites)} form site labels -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
